Make compile script fail if something goes wrong, add test suite

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
-set -o errexit
+set -e
+set -o errexit    # always exit on error
+set -o pipefail   # don't ignore exit codes when piping output
 
 function error() {
   echo " !     $*" >&2
